[versions]
agp = "8.2.0"
kotlin = "1.9.21"

androidx-core-ktx = "1.12.0"
android-tools = "31.3.0-alpha18"
android-tools-dexlib2 = "3.0.3"
assertk = "0.28.0"
detekt = "1.23.4"
diktat = "1.2.5"
firebase = "32.6.0"
fbase-config-generator-gradle-plugin = "0.1-SNAPSHOT"
gradle-plugin-publish = "1.2.1"
junit5 = "5.10.1"
kotest = "5.8.0"
kotlin-compile-testing-fork = "0.4.0"
kotlinpoet = "1.15.3"
kotlinx-binary-compatibility-validator = "0.13.2"
mockk = "1.13.8"
spotless = "6.23.3"

[libraries]
agp-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
agp-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
android-tools-apkparser-apkanalyzer = { group = "com.android.tools.apkparser", name = "apkanalyzer", version.ref = "android-tools" }
android-tools-apkparser-binary-resources = { group = "com.android.tools.apkparser", name = "binary-resources", version.ref = "android-tools" }
android-tools-smali-dexlib2 = { group = "com.android.tools.smali", name = "smali-dexlib2", version.ref = "android-tools-dexlib2" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core" }
kotest-bom = { group = "io.kotest", name = "kotest-bom", version.ref = "kotest" }
kotlin-compile-testing = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kotlin-compile-testing-fork" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk"}

# Dependencies of the included build-logic
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-plugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
diktat-plugin = { group = "org.cqfn.diktat", name = "diktat-gradle-plugin", version.ref = "diktat" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
fbase-config-generator-gradle-plugin = { id = "ru.pixnews.gradle.fbase", version.ref = "fbase-config-generator-gradle-plugin" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binary-compatibility-validator" }
